package src

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"time"
)

// TrainingConfig defines the configuration for a training job
type TrainingConfig struct {
	ModelPath     string           `json:"model_path"`
	DatasetPath   string           `json:"dataset_path"`
	TensorPreload TensorPreloadCfg `json:"tensor_preload"`
	Command       CommandCfg       `json:"command"`
	NodeTopology  NodeTopologyCfg  `json:"node_topology"`
	OutputDir     string           `json:"output_dir"`
	Rank          int              `json:"rank"`       // Node rank in the cluster
	WorldSize     int              `json:"world_size"` // Total nodes in the cluster
	NodeIP        string           `json:"node_ip"`    // IP address of this node
}

type TensorPreloadCfg struct {
	Enabled   bool   `json:"enabled"`
	Threads   int    `json:"threads"`
	RedisHost string `json:"redis_host"`
	RedisPort int    `json:"redis_port"`
	RunID     string `json:"run_id"` // Consistent run ID for all nodes
}

type CommandCfg struct {
	BaseParams     string `json:"base_params"`
	AdvancedParams string `json:"advanced_params"`
}

type NodeTopologyCfg struct {
	Head    string   `json:"head"`
	Workers []string `json:"workers"`
}

// preloaderCmd stores the preloader process for cleanup
var preloaderCmd *exec.Cmd
var preloaderMutex sync.Mutex

// TrainingManager handles the execution of training tasks
type TrainingManager struct {
	config *MindletConfig
	logger *Logger
	runID  string
}

// NewTrainingManager creates a new training manager
func NewTrainingManager(config *MindletConfig, logger *Logger) (*TrainingManager, error) {
	return &TrainingManager{
		config: config,
		logger: logger,
	}, nil
}

// LoadTrainingConfig loads a training configuration from a file
func (t *TrainingManager) LoadTrainingConfig(path string) (*TrainingConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read training config: %v", err)
	}

	var config TrainingConfig
	if err := json.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("failed to parse training config: %v", err)
	}

	// Check for required fields
	if config.ModelPath == "" {
		return nil, fmt.Errorf("model_path is required")
	}
	if config.DatasetPath == "" {
		return nil, fmt.Errorf("dataset_path is required")
	}
	if config.NodeIP == "" {
		return nil, fmt.Errorf("node_ip is required")
	}
	if config.Rank < 0 {
		return nil, fmt.Errorf("rank must be >= 0")
	}
	if config.WorldSize <= 0 {
		return nil, fmt.Errorf("world_size must be > 0")
	}

	// Set defaults if not specified
	if config.TensorPreload.RedisHost == "" {
		config.TensorPreload.RedisHost = config.NodeTopology.Head
	}
	if config.TensorPreload.RedisPort == 0 {
		config.TensorPreload.RedisPort = 6379
	}
	if config.TensorPreload.Threads == 0 {
		config.TensorPreload.Threads = 64
	}
	if config.OutputDir == "" {
		config.OutputDir = "/mnt/nfs_shared/output"
	}

	return &config, nil
}

// StartTensorPreloader starts the tensor preloader process in a managed goroutine
func (t *TrainingManager) StartTensorPreloader(ctx context.Context, trainingCfg *TrainingConfig) error {
	if !trainingCfg.TensorPreload.Enabled {
		t.logger.Info("Training", "Tensor preloading is disabled")
		return nil
	}

	// Use the run ID from the config (generated by orchestration)
	runID := trainingCfg.TensorPreload.RunID
	if runID == "" {
		runID = fmt.Sprintf("train-%s", GenerateUUID())
		t.logger.Warn("Training", "No run ID provided, generated: %s", runID)
	}
	t.runID = runID

	// If this is the head node, ensure Redis is running and ready
	if trainingCfg.Rank == 0 {
		// Start Redis first
		if err := ensureRedisRunning(trainingCfg.TensorPreload.RedisPort); err != nil {
			return fmt.Errorf("failed to ensure Redis is running: %w", err)
		}
		t.logger.Info("Training", "Redis server is ready on port %d", trainingCfg.TensorPreload.RedisPort)
	} else {
		// For worker nodes, wait to ensure head node has Redis up and running
		t.logger.Info("Training", "Worker node: waiting for Redis to be available on %s:%d",
			trainingCfg.TensorPreload.RedisHost, trainingCfg.TensorPreload.RedisPort)

		// Try to ping Redis to ensure it's ready
		maxRetries := 30 // 30 seconds max wait
		for i := 0; i < maxRetries; i++ {
			if isRedisAvailable(trainingCfg.TensorPreload.RedisHost, trainingCfg.TensorPreload.RedisPort) {
				t.logger.Info("Training", "Successfully connected to Redis on %s:%d",
					trainingCfg.TensorPreload.RedisHost, trainingCfg.TensorPreload.RedisPort)
				break
			}
			if i == maxRetries-1 {
				return fmt.Errorf("failed to connect to Redis after %d attempts", maxRetries)
			}
			time.Sleep(1 * time.Second)
			t.logger.Info("Training", "Waiting for Redis server... (attempt %d/%d)", i+1, maxRetries)
		}
	}

	// Construct the preloader command
	preloaderMutex.Lock()
	preloaderCmd = exec.Command(
		"python",
		filepath.Join(t.config.ProjectRoot, "workspace/torchtitan/model_loader.py"),
		trainingCfg.ModelPath,
		"--threads", fmt.Sprintf("%d", trainingCfg.TensorPreload.Threads),
		"--rank", fmt.Sprintf("%d", trainingCfg.Rank),
		"--world-size", fmt.Sprintf("%d", trainingCfg.WorldSize),
		"--redis-host", trainingCfg.TensorPreload.RedisHost,
		"--redis-port", fmt.Sprintf("%d", trainingCfg.TensorPreload.RedisPort),
		"--run-id", runID,
	)
	preloaderMutex.Unlock()

	// Use the workspace directory as working directory
	preloaderCmd.Dir = filepath.Join(t.config.ProjectRoot, "workspace")

	// Connect stdout and stderr for logging
	stdout, err := preloaderCmd.StdoutPipe()
	if err != nil {
		return fmt.Errorf("failed to create stdout pipe: %v", err)
	}
	stderr, err := preloaderCmd.StderrPipe()
	if err != nil {
		return fmt.Errorf("failed to create stderr pipe: %v", err)
	}

	t.logger.Info("Training", "Starting tensor preloader with command: %s", preloaderCmd.String())

	// Start command
	if err := preloaderCmd.Start(); err != nil {
		return fmt.Errorf("failed to start tensor preloader: %v", err)
	}

	// Create a goroutine to monitor the process
	go func() {
		// Create channels for the process completion and context cancellation
		done := make(chan error, 1)
		go func() {
			done <- preloaderCmd.Wait()
		}()

		// Process stdout/stderr
		go processOutput(stdout, func(line string) {
			t.logger.Info("TensorLoader", "%s", line)
		})
		go processOutput(stderr, func(line string) {
			t.logger.Error("TensorLoader", "%s", line)
		})

		// Wait for either process completion or context cancellation
		select {
		case err := <-done:
			if err != nil {
				t.logger.Error("Training", "Tensor preloader exited with error: %v", err)
			} else {
				t.logger.Info("Training", "Tensor preloader completed successfully")
			}
		case <-ctx.Done():
			t.logger.Info("Training", "Context cancelled, killing tensor preloader")
			preloaderMutex.Lock()
			if preloaderCmd != nil && preloaderCmd.Process != nil {
				preloaderCmd.Process.Kill()
			}
			preloaderMutex.Unlock()
		}
	}()

	t.logger.Info("Training", "Tensor preloader started with PID %d", preloaderCmd.Process.Pid)
	return nil
}

// StartTraining starts the training process
func (t *TrainingManager) StartTraining(ctx context.Context, trainingCfg *TrainingConfig) error {
	// Find the training script
	scriptPath := filepath.Join(t.config.ProjectRoot, "scripts/run_training.sh")
	if _, err := os.Stat(scriptPath); os.IsNotExist(err) {
		return fmt.Errorf("training script not found at %s", scriptPath)
	}

	// Save the config to a temporary file
	tmpConfigPath := filepath.Join(os.TempDir(), "training_config_tmp.json")
	configData, err := json.MarshalIndent(trainingCfg, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal config: %v", err)
	}
	if err := os.WriteFile(tmpConfigPath, configData, 0644); err != nil {
		return fmt.Errorf("failed to write config file: %v", err)
	}

	// Construct command to run the training script
	preloadFlag := "true"
	if !trainingCfg.TensorPreload.Enabled {
		preloadFlag = "false"
	}

	cmd := exec.Command(scriptPath,
		"--config", tmpConfigPath,
		"--preload", preloadFlag)

	// Connect stdout and stderr for logging
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return fmt.Errorf("failed to create stdout pipe: %v", err)
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return fmt.Errorf("failed to create stderr pipe: %v", err)
	}

	t.logger.Info("Training", "Starting training script: %s", cmd.String())

	// Start the script
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("failed to start training script: %v", err)
	}

	// Process stdout/stderr
	go processOutput(stdout, func(line string) {
		t.logger.Info("Training", "%s", line)
	})
	go processOutput(stderr, func(line string) {
		t.logger.Error("Training", "%s", line)
	})

	// Get the process ID for monitoring
	pid := cmd.Process.Pid
	t.logger.Info("Training", "Training script started with PID %d", pid)

	// Setup a goroutine to monitor the training process
	go func() {
		// Wait for either process completion or context cancellation
		done := make(chan error, 1)
		go func() {
			done <- cmd.Wait()
		}()

		select {
		case err := <-done:
			if err != nil {
				t.logger.Error("Training", "Training script exited with error: %v", err)
			} else {
				t.logger.Info("Training", "Training script completed successfully")
			}

			// Clean up tensor preloader if it's still running
			preloaderMutex.Lock()
			if preloaderCmd != nil && preloaderCmd.Process != nil {
				t.logger.Info("Training", "Stopping tensor preloader after training completion")
				preloaderCmd.Process.Kill()
				preloaderCmd = nil
			}
			preloaderMutex.Unlock()

			// Clean up the temporary config file
			os.Remove(tmpConfigPath)

		case <-ctx.Done():
			t.logger.Info("Training", "Context cancelled, killing training process")
			if cmd.Process != nil {
				cmd.Process.Kill()
			}

			// Clean up the temporary config file
			os.Remove(tmpConfigPath)
		}
	}()

	return nil
}

// Helper function to process command output
func processOutput(r io.Reader, logFn func(string)) {
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		logFn(scanner.Text())
	}
}

// Helper function to ensure Redis is running
func ensureRedisRunning(port int) error {
	// Check if Redis is running
	checkCmd := exec.Command("docker", "ps", "--filter", "name=redis", "--format", "{{.Names}}")
	output, err := checkCmd.Output()
	if err != nil {
		return fmt.Errorf("failed to check Redis status: %v", err)
	}

	if len(output) == 0 {
		// Start Redis
		startCmd := exec.Command("docker", "run", "--name", "redis", "-p", fmt.Sprintf("%d:6379", port), "-d", "redis")
		if err := startCmd.Run(); err != nil {
			return fmt.Errorf("failed to start Redis: %v", err)
		}

		// Give Redis a moment to initialize
		time.Sleep(2 * time.Second)
	} else {
		// Flush Redis
		flushCmd := exec.Command("docker", "exec", "redis", "redis-cli", "FLUSHALL")
		if err := flushCmd.Run(); err != nil {
			return fmt.Errorf("failed to flush Redis: %v", err)
		}
	}

	// Verify Redis is actually running by attempting to connect
	return checkRedisConnection(port)
}

// Helper function to check if Redis is running locally
func checkRedisConnection(port int) error {
	// Try to ping Redis
	pingCmd := exec.Command("docker", "exec", "redis", "redis-cli", "ping")
	output, err := pingCmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to ping Redis: %v (output: %s)", err, string(output))
	}

	// "PONG" response indicates Redis is running
	if string(output) != "PONG\n" {
		return fmt.Errorf("unexpected Redis ping response: %s", string(output))
	}

	return nil
}

// Helper function to check if Redis is available at the specified host and port
func isRedisAvailable(host string, port int) bool {
	// Use netcat to check if Redis port is open
	cmd := exec.Command("nc", "-z", "-w", "1", host, fmt.Sprintf("%d", port))
	err := cmd.Run()
	return err == nil
}
